"use client";

// app/terms/page.jsx
import { FileText } from 'lucide-react';

export default function TermsPage() {
    return (
        <div className="min-h-screen bg-[#0f0518] text-slate-300 font-sans selection:bg-red-500 selection:text-white">
            <div className="container mx-auto px-4 py-16 max-w-3xl">
                <header className="mb-12 border-b border-white/10 pb-8">
                    <div className="flex items-center gap-3 mb-6">
                        <FileText className="h-8 w-8 text-red-500" />
                        <span className="text-2xl font-bold text-white">DocuSync AI</span>
                    </div>
                    <h1 className="text-4xl font-bold text-white mb-4">Terms of Service</h1>
                    <p className="text-slate-400">Last Updated: November 2025</p>
                </header>

                <article className="prose prose-invert prose-red max-w-none">
                    <h3>1. Acceptance of Terms</h3>
                    <p>
                        By accessing or using DocuSync AI ("the Service"), you agree to be bound by these Terms.
                        If you disagree with any part of the terms, you may not access the Service.
                    </p>

                    <h3>2. Beta Access ("The Velvet Rope")</h3>
                    <p>
                        The Service is currently in a "Private Beta" phase.
                        We reserve the right to limit access, revoke accounts, or introduce waitlists at our sole discretion to maintain infrastructure stability.
                    </p>

                    <h3>3. AI Disclaimer (The "Hallucination" Clause)</h3>
                    <p className="bg-red-900/20 border-l-4 border-red-500 p-4 rounded-r">
                        <strong>Critical Warning:</strong> DocuSync AI uses Large Language Models (LLMs) to generate documentation.
                        LLMs can make mistakes ("hallucinations"). You acknowledge that DocuSync AI may generate incorrect, misleading, or insecure documentation.
                        <strong>You are solely responsible for reviewing and verifying all generated documentation before relying on it.</strong>
                    </p>

                    <h3>4. Intellectual Property</h3>
                    <p>
                        <strong>Your Code:</strong> You retain full ownership of all source code you process through DocuSync. We claim no rights to your intellectual property.
                        <br />
                        <strong>Generated Output:</strong> You own the documentation generated by the Service.
                    </p>

                    <h3>5. Acceptable Use</h3>
                    <p>You agree not to use the Service to:</p>
                    <ul>
                        <li>Process malicious code designed to exploit our infrastructure.</li>
                        <li>Reverse engineer our API or internal logic.</li>
                        <li>Bypass rate limits or queue mechanisms.</li>
                    </ul>

                    <h3>6. Liability Limitation</h3>
                    <p>
                        To the maximum extent permitted by law, DocuSync AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages,
                        including loss of profits or data, resulting from your use of the Service.
                    </p>

                    <h3>7. Termination</h3>
                    <p>
                        We may terminate or suspend your account immediately, without prior notice or liability, for any reason whatsoever, including without limitation if you breach the Terms.
                    </p>
                </article>

                <footer className="mt-16 pt-8 border-t border-white/10 text-center">
                    <a href="/" className="text-slate-400 hover:text-white transition-colors">← Back to Home</a>
                </footer>
            </div>
        </div>


    );
}